FROM golang:alpine as builder

WORKDIR $GOPATH/src/github.com/turnon/smzdm
COPY *.go ./

RUN apk add --no-cache git \
    && go get ./... \
    && go build -o /smzdm \
    && apk del git

FROM alpine:latest

WORKDIR /bin/
COPY --from=builder /smzdm .
RUN chmod +x /bin/smzdm

CMD /bin/smzdm -w